// src/app/(dashboard)/documents/DocumentClient.tsx
"use client";

import { useState } from "react";
import { FileText, Search, ArrowRightLeft, Undo2, Wrench, Printer, Calendar } from "lucide-react";
import { format } from "date-fns";

interface DocumentClientProps {
  initialData: {
    handovers: any[];
    recalls: any[];
    repairs: any[];
  };
  templates?: any[]; 
}

export default function DocumentClient({ initialData, templates = [] }: DocumentClientProps) {
  const [activeTab, setActiveTab] = useState<"HANDOVER" | "RECALL" | "REPAIR">("HANDOVER");
  const [searchTerm, setSearchTerm] = useState("");
  const [previewDoc, setPreviewDoc] = useState<any | null>(null);

  // 1. LẤY CẤU TRÚC PHÔI (TEMPLATE) THEO TAB
  const templateId = activeTab === "REPAIR" ? "MAINTENANCE" : activeTab;
  const activeTemplate = templates.find((t: any) => t.id === templateId) || {
    companyName: "DAEHA CABLE VINA CO., LTD",
    subHeader: "HỆ THỐNG QUẢN LÝ TÀI SẢN MẠNG MES",
    title: activeTab === "HANDOVER" ? "BIÊN BẢN BÀN GIAO THIẾT BỊ" : activeTab === "RECALL" ? "BIÊN BẢN THU HỒI TÀI SẢN" : "BIÊN BẢN SỬA CHỮA",
    partyALabel: "Bên Giao / Quản lý",
    partyBLabel: "Bên Nhận / Nhân sự",
    legalTerms: "Thực hiện theo quy chuẩn quản lý tài sản nhà máy...",
    footerText: "Generated by MES Assets Management"
  };

  // 2. TÌM KIẾM THEO MÃ, TÊN
  const getFilteredList = () => {
    const list = 
      activeTab === "HANDOVER" ? initialData.handovers :
      activeTab === "RECALL" ? initialData.recalls : initialData.repairs;

    return list.filter((item: any) => {
      const assetCode = item.asset?.assetCode?.toLowerCase() || "";
      const assetName = item.asset?.name?.toLowerCase() || "";
      const personName = (item.user?.name || item.creator?.name || "").toLowerCase();
      
      return assetCode.includes(searchTerm.toLowerCase()) || 
             assetName.includes(searchTerm.toLowerCase()) || 
             personName.includes(searchTerm.toLowerCase());
    });
  };

  const filteredList = getFilteredList();

  const handleTriggerPrint = (doc: any) => {
    const typeParam = activeTab === "REPAIR" ? "maintenance" : activeTab.toLowerCase();
    window.open(`/documents/print/${typeParam}/${doc.id}`, '_blank');
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 relative">
      {/* CỘT TRÁI: BẢNG DỮ LIỆU */}
      <div className="lg:col-span-2 space-y-4">
        <div className="bg-white p-1 rounded-xl border border-gray-200 shadow-sm flex text-sm font-bold text-gray-500">
          <button 
            onClick={() => { setActiveTab("HANDOVER"); setSearchTerm(""); setPreviewDoc(null); }}
            className={`flex-1 py-2.5 rounded-lg flex items-center justify-center gap-2 transition ${activeTab === "HANDOVER" ? "bg-blue-50 text-samsung" : "hover:text-gray-900"}`}
          >
            <ArrowRightLeft className="h-4 w-4" /> Bàn giao (Cấp phát)
          </button>
          <button 
            onClick={() => { setActiveTab("RECALL"); setSearchTerm(""); setPreviewDoc(null); }}
            className={`flex-1 py-2.5 rounded-lg flex items-center justify-center gap-2 transition ${activeTab === "RECALL" ? "bg-amber-50 text-amber-600" : "hover:text-gray-900"}`}
          >
            <Undo2 className="h-4 w-4" /> Thu hồi tài sản
          </button>
          <button 
            onClick={() => { setActiveTab("REPAIR"); setSearchTerm(""); setPreviewDoc(null); }}
            className={`flex-1 py-2.5 rounded-lg flex items-center justify-center gap-2 transition ${activeTab === "REPAIR" ? "bg-purple-50 text-purple-600" : "hover:text-gray-900"}`}
          >
            <Wrench className="h-4 w-4" /> Bảo dưỡng
          </button>
        </div>

        <div className="relative bg-white rounded-lg shadow-sm border border-gray-200">
          <Search className="absolute left-3 top-2.5 h-4 w-4 text-gray-400" />
          <input 
            type="text"
            placeholder="Tìm mã AST, Số Serial hoặc Tên nhân sự..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-9 pr-4 py-2 rounded-lg text-sm outline-none focus:ring-1 focus:ring-samsung bg-white text-gray-800"
          />
        </div>

        <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm whitespace-nowrap">
              <thead className="bg-gray-50 border-b border-gray-100 text-gray-500 text-xs font-bold uppercase tracking-wider">
                <tr>
                  <th className="px-5 py-3.5">Mã tài sản / Văn bản</th>
                  <th className="px-5 py-3.5">Nhân sự liên quan</th>
                  <th className="px-5 py-3.5">Ngày ghi nhận</th>
                  <th className="px-5 py-3.5 text-right">Tác vụ</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100 text-gray-700">
                {filteredList.map((doc: any) => {
                  const targetUser = doc.user?.name || doc.creator?.name || "N/A";
                  const targetDept = doc.user?.department?.name || doc.creator?.department?.name || "Nhà xưởng";
                  const targetDate = doc.assignedDate || doc.returnDate || doc.createdAt;

                  return (
                    <tr key={doc.id} className="hover:bg-gray-50/50 transition-colors">
                      <td className="px-5 py-3.5">
                        <div className="flex flex-col">
                          <span className="font-black text-samsung">{doc.asset?.assetCode}</span>
                          <span className="text-xs text-gray-500 font-medium truncate max-w-200px">{doc.asset?.name}</span>
                        </div>
                      </td>
                      <td className="px-5 py-3.5">
                        <div className="flex flex-col">
                          <span className="font-bold text-gray-800">{targetUser}</span>
                          <span className="text-xs text-gray-400 font-semibold">{targetDept}</span>
                        </div>
                      </td>
                      <td className="px-5 py-3.5 text-xs font-medium text-gray-500 flex items-center gap-1.5 pt-5">
                        <Calendar className="h-3.5 w-3.5 text-gray-400" />
                        {format(new Date(targetDate), "dd/MM/yyyy HH:mm")}
                      </td>
                      <td className="px-5 py-3.5 text-right">
                        <div className="flex justify-end gap-2">
                          <button 
                            onClick={() => setPreviewDoc(doc)}
                            className="px-3 py-1.5 text-xs font-bold border rounded-lg bg-gray-50 text-gray-600 hover:bg-gray-100 transition shadow-sm"
                          >
                            Xem
                          </button>
                          <button 
                            onClick={() => handleTriggerPrint(doc)}
                            className="px-2.5 py-1.5 border border-emerald-200 text-emerald-700 bg-emerald-50 hover:bg-emerald-100 rounded-lg text-xs font-bold transition flex items-center gap-1 shadow-sm"
                          >
                            <Printer className="h-3.5 w-3.5" /> In phiếu
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}

                {filteredList.length === 0 && (
                  <tr>
                    <td colSpan={4} className="px-5 py-12 text-center text-gray-400 font-medium">
                      Không tìm thấy văn bản phù hợp.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* CỘT PHẢI: KHUNG PREVIEW ĐỒNG BỘ PHÔI */}
      <div className={`lg:col-span-1 ${previewDoc ? 'block' : 'hidden lg:block'}`}>
        {previewDoc ? (
          <div className="bg-white border border-gray-200 shadow-lg rounded-2xl p-6 space-y-6 text-gray-900 font-serif sticky top-6">
            
            <div className="text-center space-y-1">
              {/* Header Phôi */}
              <h3 className="font-bold text-xs uppercase tracking-wide text-gray-800">{activeTemplate.companyName}</h3>
              <p className="text-[10px] font-bold uppercase text-gray-500 border-b pb-2 tracking-widest">HỆ THỐNG QUẢN LÝ TÀI SẢN MẠNG MES</p>
              
              <div className="pt-4">
                <h2 className="font-black text-base uppercase text-gray-900 tracking-wide">
                  {activeTemplate.title}
                </h2>
                <p className="text-[10px] italic text-gray-600 font-sans mt-0.5">{activeTemplate.subHeader}</p>
              </div>
            </div>

            <div className="text-xs space-y-3 pt-4 font-sans text-gray-800">
              <p>📌 <strong>Thời gian:</strong> {format(new Date(previewDoc.assignedDate || previewDoc.returnDate || previewDoc.createdAt), "dd/MM/yyyy HH:mm")}</p>
              
              <div className="border-t border-dashed pt-3 space-y-1.5">
                <h4 className="font-bold text-gray-900 text-[11px] underline mb-2">I. THÔNG TIN BÊN GIAO / BÊN NHẬN</h4>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <p className="font-bold text-gray-800 uppercase text-[9px] mb-1">{activeTemplate.partyALabel}</p>
                    <p>• <strong>Đại diện:</strong> Nguyễn Văn A (IT)</p>
                  </div>
                  <div>
                    <p className="font-bold text-gray-800 uppercase text-[9px] mb-1">{activeTemplate.partyBLabel}</p>
                    <p>• <strong>Đại diện:</strong> {previewDoc.user?.name || previewDoc.creator?.name || "N/A"}</p>
                    <p className="text-[10px] text-gray-500">({previewDoc.user?.department?.name || previewDoc.creator?.department?.name || "Xưởng sản xuất"})</p>
                  </div>
                </div>
              </div>

              <div className="border-t border-dashed pt-3 space-y-1.5">
                <h4 className="font-bold text-gray-900 text-[11px] underline">II. THÔNG TIN THIẾT BỊ</h4>
                <p>• <strong>Mã quản lý:</strong> <span className="font-bold text-samsung">{previewDoc.asset?.assetCode}</span></p>
                <p>• <strong>Tên thiết bị:</strong> {previewDoc.asset?.name}</p>
                <p>• <strong>Số Serial:</strong> <span className="uppercase font-mono">{previewDoc.asset?.serialNumber}</span></p>
              </div>

              <div className="border-t border-dashed pt-3 space-y-1.5">
                <h4 className="font-bold text-gray-900 text-[11px] underline">III. NỘI DUNG GHI NHẬN</h4>
                <div className="p-2.5 bg-gray-50 border rounded-lg text-xs text-gray-600 italic">
                  {previewDoc.remark || previewDoc.description || "Máy đang hoạt động bình thường, xuất kho theo quy định."}
                </div>
              </div>
            </div>

            {/* Điều khoản pháp lý */}
            <div className="border-t border-dashed pt-3">
               <p className="text-[10px] italic text-gray-500 leading-relaxed text-justify">{activeTemplate.legalTerms}</p>
            </div>

            {/* Chữ ký */}
            <div className="grid grid-cols-2 text-center text-xs font-sans pt-6 text-gray-800">
              <div>
                <p className="font-bold text-gray-800 uppercase text-[10px]">{activeTemplate.partyALabel}</p>
                <p className="text-[10px] text-gray-400 italic mt-0.5">(Ký, ghi rõ họ tên)</p>
                <div className="h-16"></div>
                <p className="font-bold text-gray-800">Nguyễn Văn A</p>
              </div>
              <div>
                <p className="font-bold text-gray-800 uppercase text-[10px]">{activeTemplate.partyBLabel}</p>
                <p className="text-[10px] text-gray-400 italic mt-0.5">(Ký, xác nhận tình trạng)</p>
                <div className="h-16"></div>
                <p className="font-bold text-gray-800">{previewDoc.user?.name || previewDoc.creator?.name || "Xác nhận"}</p>
              </div>
            </div>
            
            <div className="text-center text-[9px] text-gray-300 font-mono pt-4 border-t border-dashed">
              {activeTemplate.footerText} - ID: {previewDoc.id.slice(0,6).toUpperCase()}
            </div>

            <button 
              onClick={() => setPreviewDoc(null)}
              className="w-full bg-gray-900 text-white py-2 text-xs font-bold rounded-xl lg:hidden"
            >
              Đóng xem trước
            </button>
          </div>
        ) : (
          <div className="bg-gray-50 border border-dashed border-gray-200 rounded-2xl p-8 text-center text-gray-400 flex flex-col items-center justify-center h-400px sticky top-6">
            <FileText className="h-10 w-10 text-gray-300 mb-3" />
            <h4 className="font-bold text-sm text-gray-600">Khung xem trước văn bản</h4>
            <p className="text-xs max-w-200px mx-auto mt-1 leading-relaxed">Vui lòng bấm "Xem" tại dòng văn bản tương ứng để đối chiếu phôi in.</p>
          </div>
        )}
      </div>
    </div>
  );
}