// src/actions/template.actions.ts
"use server";

import { prisma } from "@/lib/prisma";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { revalidatePath } from "next/cache";

// 1. Lấy danh sách tất cả các biểu mẫu mẫu
export async function getFormTemplates() {
  try {
    const templates = await prisma.formTemplate.findMany({
      orderBy: { id: "asc" }
    });
    
    // Nếu DB trống, tự động tạo dữ liệu mồi ban đầu (Seed data)
    if (templates.length === 0) {
      const defaultTemplates = [
        {
          id: "HANDOVER",
          name: "Biên bản Bàn giao tài sản",
          title: "BIÊN BẢN BÀN GIAO TÀI SẢN",
          companyName: "CÔNG TY TNHH DAEHA CABLE VINA",
          subHeader: "Căn cứ vào quy định quản lý tài sản và nhu cầu thực tế tại nhà máy.",
          partyALabel: "Bên giao (Phòng Quản lý/IT)",
          partyBLabel: "Bên nhận (Người sử dụng)",
          legalTerms: "Biên bản được lập thành 02 bản có giá trị pháp lý như nhau, mỗi bên giữ 01 bản để làm cơ sở đối chiếu. Trách nhiệm bảo quản tài sản thuộc về Bên nhận kể từ thời điểm ký.",
          footerText: "Generated by MES Assets Management System - Handover Template"
        },
        {
          id: "RECALL",
          name: "Biên bản Thu hồi tài sản",
          title: "BIÊN BẢN THU HỒI TÀI SẢN",
          companyName: "CÔNG TY TNHH DAEHA CABLE VINA",
          subHeader: "Căn cứ theo quyết định điều chuyển hoặc thu hồi công cụ dụng cụ xưởng.",
          partyALabel: "Bên thu hồi (Phòng Quản lý/IT)",
          partyBLabel: "Bên bàn giao lại (Người sử dụng)",
          legalTerms: "Biên bản xác nhận thiết bị đã được hoàn trả lại cho kho quản lý trung tâm. Mọi trách nhiệm vận hành trước đó của người sử dụng được giải trừ.",
          footerText: "Generated by MES Assets Management System - Recall Template"
        }
      ];

      await prisma.formTemplate.createMany({ data: defaultTemplates });
      return { success: true, data: defaultTemplates };
    }

    return { success: true, data: templates };
  } catch (error) {
    return { success: false, error: "Không thể tải cấu trúc biểu mẫu." };
  }
}

// 2. Cập nhật nội dung tùy chỉnh của một biểu mẫu
export async function updateFormTemplate(id: string, data: any) {
  try {
    const session = await getServerSession(authOptions);
    if ((session?.user as any)?.role !== "ADMIN") {
      return { success: false, error: "Từ chối truy cập. Bạn không có quyền cấu hình." };
    }

    await prisma.formTemplate.update({
      where: { id },
      data: {
        title: data.title.trim(),
        companyName: data.companyName.trim(),
        subHeader: data.subHeader.trim(),
        partyALabel: data.partyALabel.trim(),
        partyBLabel: data.partyBLabel.trim(),
        legalTerms: data.legalTerms.trim(),
        footerText: data.footerText.trim(),
      }
    });

    revalidatePath("/documents");
    return { success: true };
  } catch (error) {
    return { success: false, error: "Lỗi hệ thống khi cập nhật biểu mẫu." };
  }
}