// src/components/assets/ProtocolDocument.tsx
"use client";

import { useState } from "react";
import { Printer, ArrowRightLeft, Undo2, Wrench, FileQuestion } from "lucide-react";

export type ProtocolType = "HANDOVER" | "RECALL" | "MAINTENANCE" | "LOST";

interface ProtocolDocumentProps {
  type: ProtocolType;
  recordId?: string;
  templateData?: any;
  dbRecord: any;
}

export default function ProtocolDocument({ type, recordId = "NEW", templateData, dbRecord }: ProtocolDocumentProps) {
  const icons = {
    HANDOVER: <ArrowRightLeft className="h-5 w-5" />,
    RECALL: <Undo2 className="h-5 w-5" />,
    MAINTENANCE: <Wrench className="h-5 w-5" />,
    LOST: <FileQuestion className="h-5 w-5" />, // Bổ sung icon cho báo mất
  };

  const companyName = templateData?.companyName || "CÔNG TY TNHH DAEHA CABLE VINA";
  const title = templateData?.title || `BIÊN BẢN ${type}`;
  const subHeader = templateData?.subHeader || "Căn cứ vào quy định quản lý tài sản nhà máy.";
  const partyALabel = templateData?.partyALabel || "Bên giao (Phòng Quản lý/IT)";
  const partyBLabel = templateData?.partyBLabel || "Bên nhận (Người sử dụng)";
  const legalTerms = templateData?.legalTerms || "Biên bản được lập thành 02 bản có giá trị pháp lý như nhau.";
  const footerText = templateData?.footerText || "Generated by MES Assets Management System";

  const targetUser = dbRecord?.user?.name || dbRecord?.creator?.name || "N/A";
  const targetDept = dbRecord?.user?.department?.name || dbRecord?.creator?.department?.name || "Nhà xưởng";
  const rawDate = dbRecord?.assignedDate || dbRecord?.returnDate || dbRecord?.createdAt || new Date();
  const formattedDate = new Date(rawDate).toISOString().split("T")[0];

  // TỰ ĐỘNG LẤY ĐỊA ĐIỂM TỪ DB NẾU CÓ, NẾU KHÔNG THÌ LÀM MẪU MẶC ĐỊNH
  const targetLocation = dbRecord?.location?.name || "văn phòng Daeha Cable Vina";

  const [formData, setFormData] = useState({
    partyAName: "Nguyễn Văn A (IT / MES Administrator)",
    partyBName: targetUser,
    department: targetDept,
    assetId: dbRecord?.asset?.assetCode || "AST-UNKNOWN",
    assetName: dbRecord?.asset?.name || "N/A",
    serial: dbRecord?.asset?.serialNumber || "N/A",
    // Ưu tiên lấy dbRecord.details cho log Báo Mất, sau đó mới đến remark/description
    condition: dbRecord?.details || dbRecord?.remark || dbRecord?.description || "Thiết bị hoạt động bình thường theo tiêu chuẩn nội bộ.",
    date: formattedDate,
    location: targetLocation
  });

  return (
    <div className="mes-print-page min-h-screen bg-gray-200 py-10 flex flex-col items-center print:bg-white print:py-0 print:m-0">
      
      {/* TOOLBAR */}
      <div className="w-full max-w-[210mm] flex justify-between items-center mb-6 print:hidden no-print">
        <div className="flex items-center gap-2 text-gray-700 font-bold text-sm">
          {icons[type]} {title} - Mã phiếu: <span className="text-samsung font-mono">{recordId}</span>
        </div>
        <button 
          onClick={() => window.print()} 
          className="flex items-center gap-2 bg-samsung text-white px-5 py-2 rounded-lg font-bold text-sm shadow-sm hover:bg-blue-700 transition"
        >
          <Printer className="h-4 w-4" /> Bấm Máy In
        </button>
      </div>

      {/* TỜ GIẤY A4 */}
      <div id="factory-printable-area" className="w-[210mm] min-h-[297mm] bg-white shadow-2xl p-[20mm] print:shadow-none print:w-full print:h-auto print:p-0 relative font-serif text-[14px]">
        
        {/* QUỐC HIỆU */}
        <div className="flex justify-between items-start border-b pb-4 mb-8">
          <div className="text-center">
            <h4 className="font-bold uppercase text-gray-800 text-xs">{companyName}</h4>
            <p className="text-[11px] font-semibold text-gray-500 mt-1">HỆ THỐNG QUẢN LÝ TÀI SẢN MẠNG MES</p>
            <p className="text-[11px] italic text-gray-400 font-mono mt-0.5">Ref: BB-{type.slice(0,3)}-{recordId.slice(0,6).toUpperCase()}</p>
          </div>
          <div className="text-center">
            <h4 className="font-bold uppercase text-gray-800 text-xs">Cộng hòa xã hội chủ nghĩa Việt Nam</h4>
            <p className="text-[12px] font-bold text-gray-700 mt-0.5">Độc lập - Tự do - Hạnh phúc</p>
            <div className="w-24 h-1px bg-gray-400 mx-auto mt-1"></div>
          </div>
        </div>

        {/* TIÊU ĐỀ */}
        <div className="text-center mb-8">
          <h1 className="text-xl font-black text-gray-900 uppercase tracking-wide">{title}</h1>
          <p className="text-xs italic text-gray-500 mt-1.5">{subHeader}</p>
        </div>

        {/* PHẦN CHỮ NỘI DUNG VÀ ĐỊA ĐIỂM CHỈNH SỬA */}
        <div className="space-y-6 text-gray-800 font-sans text-sm">
          <p className="leading-relaxed">
            Hôm nay, ngày 
            <input 
              type="date" 
              value={formData.date} 
              onChange={e => setFormData({...formData, date: e.target.value})} 
              className="mx-1 border-b border-dashed border-gray-400 outline-none font-bold text-samsung print:text-black print:border-none bg-transparent" 
            />
            , tại 
            <input 
              type="text" 
              value={formData.location} 
              onChange={e => setFormData({...formData, location: e.target.value})} 
              placeholder="văn phòng công ty..."
              className="mx-1 px-1 border-b border-dashed border-gray-400 outline-none font-bold text-samsung print:text-black print:border-none bg-transparent min-w-220px focus:border-samsung"
            />
            , các bên gồm có:
          </p>

          <div className="grid grid-cols-2 gap-6 bg-gray-50 p-4 rounded-xl border print:bg-transparent print:border-none print:p-0">
            <div>
              <h3 className="font-bold uppercase text-xs mb-2 underline text-gray-700">{partyALabel}</h3>
              <div className="space-y-1.5 text-xs">
                <div className="flex"><span className="w-20 text-gray-400">Đại diện:</span> <input value={formData.partyAName} onChange={e => setFormData({...formData, partyAName: e.target.value})} className="flex-1 font-bold outline-none bg-transparent border-b border-dashed print:border-none" /></div>
                <div className="flex"><span className="w-20 text-gray-400">Bộ phận:</span> <span className="font-semibold">Phòng Kỹ thuật IT / MES</span></div>
              </div>
            </div>
            <div>
              <h3 className="font-bold uppercase text-xs mb-2 underline text-gray-700">{partyBLabel}</h3>
              <div className="space-y-1.5 text-xs">
                <div className="flex"><span className="w-20 text-gray-400">Đại diện:</span> <input value={formData.partyBName} onChange={e => setFormData({...formData, partyBName: e.target.value})} className="flex-1 font-bold outline-none bg-transparent border-b border-dashed print:border-none" /></div>
                <div className="flex"><span className="w-20 text-gray-400">Bộ phận:</span> <input value={formData.department} onChange={e => setFormData({...formData, department: e.target.value})} className="flex-1 font-semibold outline-none bg-transparent border-b border-dashed print:border-none" /></div>
              </div>
            </div>
          </div>

          <p>Cùng bàn giao và xác thực hiện trạng thiết bị phần cứng cụ thể như sau:</p>

          <table className="w-full border-collapse border border-gray-400 text-xs">
            <thead>
              <tr className="bg-gray-100 print:bg-transparent border-b border-gray-400">
                <th className="border border-gray-400 p-2 w-12 text-center">STT</th>
                <th className="border border-gray-400 p-2 text-left">Mã Quản Lý</th>
                <th className="border border-gray-400 p-2 text-left">Tên Thiết Bị / Model</th>
                <th className="border border-gray-400 p-2 text-left">Số Serial Number</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="border border-gray-400 p-2.5 text-center font-bold">01</td>
                <td className="border border-gray-400 p-2.5 font-bold font-mono text-samsung print:text-black">{formData.assetId}</td>
                <td className="border border-gray-400 p-2.5 font-medium">{formData.assetName}</td>
                <td className="border border-gray-400 p-2.5 font-mono uppercase text-gray-600">{formData.serial}</td>
              </tr>
            </tbody>
          </table>

          <div className="space-y-3">
            <div>
              <label className="font-bold text-xs underline block text-gray-700">Tình trạng / Nội dung ghi nhận thực tế:</label>
              <textarea value={formData.condition} onChange={e => setFormData({...formData, condition: e.target.value})} className="w-full h-16 mt-1 p-2 border rounded outline-none focus:ring-1 focus:ring-samsung text-xs bg-transparent print:border-none print:p-0 print:h-auto resize-none" />
            </div>
          </div>

          <p className="italic text-xs text-gray-500 text-justify leading-relaxed">{legalTerms}</p>
        </div>

        {/* CHỮ KÝ */}
        <div className="mt-12 grid grid-cols-2 text-center pb-16">
          <div>
            <h4 className="font-bold text-xs uppercase">{partyALabel}</h4>
            <p className="text-[11px] text-gray-400 italic mt-0.5">(Ký và ghi rõ họ tên)</p>
            <div className="h-20"></div>
            <p className="font-bold text-gray-700 text-xs uppercase">{formData.partyAName}</p>
          </div>
          <div>
            <h4 className="font-bold text-xs uppercase">{partyBLabel}</h4>
            <p className="text-[11px] text-gray-400 italic mt-0.5">(Ký, xác nhận)</p>
            <div className="h-20"></div>
            <p className="font-bold text-gray-800 text-xs uppercase">{formData.partyBName}</p>
          </div>
        </div>

        {/* FOOTER */}
        <div className="absolute bottom-[8mm] left-[20mm] w-[calc(100%-40mm)] text-center text-[9px] text-gray-300 font-mono border-t border-dashed pt-1.5 print:text-gray-400">
          {footerText} - System ID: {recordId}
        </div>
      </div>

      <style dangerouslySetInnerHTML={{ __html: `
        @media print {
          body * {
            visibility: hidden !important;
          }
          #factory-printable-area, #factory-printable-area * {
            visibility: visible !important;
          }
          #factory-printable-area {
            position: absolute !important;
            left: 0 !important;
            top: 0 !important;
            width: 100% !important;
            border: none !important;
            box-shadow: none !important;
            padding: 0 !important;
          }
          .no-print, button, aside, nav {
            display: none !important;
          }
        }
      `}} />
    </div>
  );
}